-- 
-- Tabellenstruktur für Tabelle `d3geoip`
-- 

CREATE TABLE `d3geoip` (
	`D3IP` VARCHAR(45) NOT NULL,
	`D3STARTIP` VARCHAR(39) NOT NULL,
	`D3ENDIP` VARCHAR(39) NOT NULL,
	`D3STARTIPBIN` VARBINARY(16) NOT NULL,
	`D3ENDIPBIN` VARBINARY(16) NOT NULL,
	`D3ISO` CHAR(2) NULL DEFAULT NULL,
	`D3COUNTRYNAME` VARCHAR(50) NULL DEFAULT NULL,
	`D3CONTINENTCODE` CHAR(2) NULL DEFAULT NULL,
	PRIMARY KEY (`D3IP`),
	INDEX `D3ISO` (`D3ISO`),
	INDEX `IPBIN` (`D3STARTIPBIN`, `D3ENDIPBIN`)
)
COMMENT='GeoIP'
COLLATE='utf8_general_ci'
ENGINE=InnoDB;
